insert into gifts (gift_name, checked, person)
values
  ('Wallet', true, 5),
  ('Mug', true, 3),
  ('Umbrella', true, 10),
  ('Ball pit', true, 6),
  ('Exfoliator brush', true, 8),
  ('Bath boat', false, 1),
  ('Automatic pan stirrer', false, 3),
  ('Lego', false, 4),
  ('Magnetic doodle board', false, 6),
  ('Scratch off world map', false, 7),
  ('Air hockey table', false, 9),
  ('Ripstick caster board', false, 1),
  ('Shower duck', false, 3),
  ('Passport holder', false, 2),
  ('Suitcase', false, 6),
  ('Poncho', false, 7),
  ('Floor seat', false, 10),
  ('Cloud message board', false, 5),
  ('Magic 8 ball', false, 9),
  ('Sling seat tub', false, 8),
  ('Puzzle foam mat', false, 9),
  ('Mini telescope', false, 10),
  ('Solar robot', false, 3),
  ('Cash register', false, 1),
  ('Laptop', false, 7),
  ('Jigsaw Puzzle', false, 7),
  ('Math wall clock', false, 9),
  ('Stack up cups', false, 8),
  ('Push & Pop Bulldozer', false, 8),
  ('Toaster', false, 6),
  ('Knee socks', false, 3),
  ('Fairy lights', false, 2),
  ('Sunglasses', false, 4),
  ('Snow globe', false, 9),
  ('Design a cap kit', false, 8),
  ('Go pro camera', false, 10),
  ('Pillow', false, 1),
  ('Hoverboard', false, 6),
  ('Light gloves', false, 4),
  ('Monopoly', false, 7),
  ('Facial cleansing spin brush', false, 6),
  ('Stuffed Animal', false, 10),
  ('Wireless printer', false, 4),
  ('Walkie Talkie', false, 7),
  ('Fake nails set', false, 2),
  ('Picture frame', false, 3),
  ('Car Seat', false, 6),
  ('Apron', false, 8),
  ('Rings', false, 5),
  ('Corn poppers', false, 5);